import { useEffect,useState } from 'react';
import axios from 'axios';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api'; const headers={headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}};
export default function Comparacion(){
 const [sectors,setSectors]=useState([]),[period,setPeriod]=useState({from:'',to:'',previousFrom:'',previousTo:'',resourceType:''}),[sector,setSector]=useState({sectorA:'',sectorB:'',from:'',to:'',resourceType:''}),[periodResult,setPeriodResult]=useState(null),[sectorResult,setSectorResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{axios.get(`${API_URL}/smart/sectores`,headers).then(r=>setSectors(r.data)).catch(()=>{});},[]);
 const comparePeriod=async e=>{e.preventDefault();try{const {data}=await axios.get(`${API_URL}/smart/consumos/comparacion`,{params:period,...headers});setPeriodResult(data);setError('');}catch{setError('Completa los períodos correctamente.');}};
 const compareSectors=async e=>{e.preventDefault();try{const {data}=await axios.get(`${API_URL}/smart/consumos/comparacion-sectores`,{params:sector,...headers});setSectorResult(data);setError('');}catch{setError('Completa sectores y fechas.');}};
 const cards=result=>result&&<div className="grid md:grid-cols-4 gap-4 mt-4">{Object.entries(result).filter(([key])=>!['sectorA','sectorB'].includes(key)).map(([key,value])=><article className="metric-card" key={key}><span>{key}</span><strong>{typeof value==='number'?value.toFixed(2):value??'—'}</strong></article>)}</div>;
 return <div className="p-6"><h2 className="text-2xl font-black mb-2">Comparación de consumos</h2><p className="text-gray-500 mb-6">Contrasta períodos o sectores en el mismo período.</p>{error&&<p className="feedback error">{error}</p>}<section className="bg-white border rounded-xl p-5 mb-6"><h3 className="font-bold mb-3">Comparar períodos</h3><form onSubmit={comparePeriod} className="grid md:grid-cols-5 gap-3"><select value={period.resourceType} onChange={e=>setPeriod({...period,resourceType:e.target.value})}><option value="">Agua y energía</option><option value="AGUA">Agua</option><option value="ENERGIA">Energía</option></select><input required type="date" value={period.from} onChange={e=>setPeriod({...period,from:e.target.value})}/><input required type="date" value={period.to} onChange={e=>setPeriod({...period,to:e.target.value})}/><input required type="date" value={period.previousFrom} onChange={e=>setPeriod({...period,previousFrom:e.target.value})}/><input required type="date" value={period.previousTo} onChange={e=>setPeriod({...period,previousTo:e.target.value})}/><button className="button button-dark md:col-span-5">Comparar períodos</button></form>{cards(periodResult)}</section><section className="bg-white border rounded-xl p-5"><h3 className="font-bold mb-3">Comparar sectores</h3><form onSubmit={compareSectors} className="grid md:grid-cols-5 gap-3"><select required value={sector.sectorA} onChange={e=>setSector({...sector,sectorA:e.target.value})}><option value="">Sector A</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select required value={sector.sectorB} onChange={e=>setSector({...sector,sectorB:e.target.value})}><option value="">Sector B</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input required type="date" value={sector.from} onChange={e=>setSector({...sector,from:e.target.value})}/><input required type="date" value={sector.to} onChange={e=>setSector({...sector,to:e.target.value})}/><select value={sector.resourceType} onChange={e=>setSector({...sector,resourceType:e.target.value})}><option value="">Agua y energía</option><option value="AGUA">Agua</option><option value="ENERGIA">Energía</option></select><button className="button button-dark md:col-span-5">Comparar sectores</button></form>{cards(sectorResult)}</section></div>;
}
