import { useEffect,useState } from 'react';
import axios from 'axios';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api'; const config=()=>({headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}});
export default function Permisos(){
 const[roles,setRoles]=useState([]),[permissions,setPermissions]=useState([]),[selected,setSelected]=useState(null),[selectedIds,setSelectedIds]=useState([]),[roleName,setRoleName]=useState(''),[editing,setEditing]=useState(null),[message,setMessage]=useState('');
 const choose=role=>{setSelected(role);setSelectedIds(role.permissions.map(x=>x.permissionId));};
 const load=async()=>{const[r,p]=await Promise.all([axios.get(`${API_URL}/smart/roles/permisos`,config()),axios.get(`${API_URL}/smart/permisos`,config())]);setRoles(r.data);setPermissions(p.data);if(!selected&&r.data[0])choose(r.data[0]);};useEffect(()=>{load().catch(()=>setMessage('No se pudieron cargar los permisos.'));},[]);
 const savePermissions=async()=>{await axios.put(`${API_URL}/smart/roles/${selected.id}/permisos`,{permissionIds:selectedIds},config());setMessage('Permisos actualizados.');load();};
 const saveRole=async e=>{e.preventDefault();try{if(editing)await axios.put(`${API_URL}/smart/roles/${editing}`,{name:roleName},config());else await axios.post(`${API_URL}/smart/roles`,{name:roleName},config());setRoleName('');setEditing(null);setMessage('Rol guardado.');load();}catch{setMessage('No se pudo guardar el rol.');}};
 const editRole=role=>{setEditing(role.id);setRoleName(role.name);}; const remove=async role=>{if(!window.confirm(`¿Eliminar ${role.name}?`))return;try{await axios.delete(`${API_URL}/smart/roles/${role.id}`,config());if(selected?.id===role.id)setSelected(null);load();}catch(error){setMessage(error.response?.data?.error||'No se pudo eliminar el rol.');}};
 const toggle=id=>setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
 return <div className="p-6"><h2 className="text-2xl font-black mb-2">Roles y permisos</h2><p className="text-gray-500 mb-5">Crea roles y define qué operaciones puede realizar cada uno.</p><form onSubmit={saveRole} className="flex gap-3 mb-5"><input required placeholder="Nombre del rol" value={roleName} onChange={e=>setRoleName(e.target.value)}/><button className="button button-dark">{editing?'Actualizar rol':'Crear rol'}</button></form><div className="grid md:grid-cols-[260px_1fr] gap-5"><aside className="bg-white border rounded-xl p-3">{roles.map(role=><div className="flex" key={role.id}><button onClick={()=>choose(role)} className={`flex-1 text-left p-3 rounded ${selected?.id===role.id?'bg-emerald-100':'hover:bg-stone-100'}`}>{role.name}</button><button onClick={()=>editRole(role)} title="Editar">✎</button><button onClick={()=>remove(role)} title="Eliminar">×</button></div>)}</aside>{selected&&<section className="bg-white border rounded-xl p-5"><h3 className="font-bold text-lg mb-4">Permisos de {selected.name}</h3><div className="grid sm:grid-cols-2 gap-3">{permissions.map(permission=><label className="flex gap-3 p-3 border rounded cursor-pointer" key={permission.id}><input type="checkbox" checked={selectedIds.includes(permission.id)} onChange={()=>toggle(permission.id)}/><span><strong>{permission.code}</strong><small className="block text-gray-500">{permission.description}</small></span></label>)}</div><button onClick={savePermissions} className="button button-dark mt-5">Guardar permisos</button></section>}</div>{message&&<p className="feedback mt-4">{message}</p>}</div>;
}
