import { useEffect,useState } from 'react';
import axios from 'axios';
import { CalendarClock,Plus,Trash2,Pencil } from 'lucide-react';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api'; const headers=()=>({headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); const empty={type:'RIEGO',sectorId:'',date:'',time:'08:00',durationMins:30,enabled:true};
export default function Programaciones(){
 const [items,setItems]=useState([]),[sectors,setSectors]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[message,setMessage]=useState('');
 const load=async()=>{const[a,b]=await Promise.all([axios.get(`${API_URL}/smart/programaciones`,headers()),axios.get(`${API_URL}/smart/sectores`,headers())]);setItems(a.data);setSectors(b.data);};useEffect(()=>{load().catch(()=>{});},[]);
 const save=async e=>{e.preventDefault();try{if(editing)await axios.put(`${API_URL}/smart/programaciones/${editing}`,form,headers());else await axios.post(`${API_URL}/smart/programaciones`,form,headers());setForm(empty);setEditing(null);setMessage('Programación guardada.');load();}catch(err){setMessage(err.response?.data?.error||'No se pudo guardar.');}};
 const edit=item=>{setEditing(item.id);setForm({type:item.type,sectorId:String(item.sectorId),date:item.date?item.date.slice(0,10):'',time:item.time,durationMins:item.durationMins,enabled:item.enabled});};
 const remove=async id=>{if(window.confirm('¿Eliminar programación?')){await axios.delete(`${API_URL}/smart/programaciones/${id}`,headers());load();}};
 return <div className="p-6"><div className="flex items-center gap-3 mb-5"><CalendarClock/><div><h2 className="text-2xl font-black">Programación operativa</h2><p>Agenda riego e iluminación por sector.</p></div></div><form onSubmit={save} className="bg-white border rounded-xl p-5 grid gap-3 md:grid-cols-6"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="RIEGO">Riego</option><option value="ILUMINACION">Iluminación</option></select><select required value={form.sectorId} onChange={e=>setForm({...form,sectorId:e.target.value})}><option value="">Sector</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input required type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/><input required min="1" type="number" value={form.durationMins} onChange={e=>setForm({...form,durationMins:e.target.value})}/><label className="flex items-center gap-2"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Activa</label><button className="button button-dark md:col-span-6"><Plus size={17}/>{editing?'Actualizar':'Agregar'}</button>{message&&<p className="feedback md:col-span-6">{message}</p>}</form><div className="mt-6 bg-white border rounded-xl overflow-hidden"><table className="min-w-full"><thead><tr><th>Actividad</th><th>Sector</th><th>Fecha</th><th>Hora</th><th>Duración</th><th>Estado</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.type}</td><td>{item.sector?.name}</td><td>{item.date?new Date(item.date).toLocaleDateString('es'):'Recurrente'}</td><td>{item.time}</td><td>{item.durationMins} min</td><td>{item.enabled?'Activa':'Pausada'}</td><td><button className="mr-3" onClick={()=>edit(item)}><Pencil size={17}/></button><button onClick={()=>remove(item.id)}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></div>;
}
